myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
]

projects/urls.py
#-*- coding:utf-8 -*-

from django.urls import path, re_path
from . import views

# namespace
app_name = 'projects'

urlpatterns = [
    # Create a project
    path('create/', views.ProjectCreateView.as_view(), name='project_create'),
    # Retrieve project list
    path('', views.ProjectListView.as_view(), name='project_list'),
    # Retrieve single project object
    re_path(r'^(?P<pk>\d+)/$', views.ProjectDetailView.as_view(), name='project_detail'),
    # Update a project
    re_path(r'^(?P<pk>\d+)/update/$', views.ProjectUpdateView.as_view(), name='project_update'),
    # Delete a project
    re_path(r'^(?P<pk>\d+)/delete/$', views.ProjectDeleteView.as_view(), name='project_delete')

    # # Create a project
    # path('create/', views.project_create, name='project_create'),
    # # Retrieve project list
    # path('', views.project_list, name='project_list'),
    # # Retrieve single project object
    # re_path(r'^(?P<pk>\d+)/$', views.project_detail, name='project_detail'),
    # # Update a project
    # re_path(r'^(?P<pk>\d+)/update/$', views.project_update, name='project_update'),
    # # Delete a project
    # re_path(r'^(?P<pk>\d+)/delete/$', views.project_delete, name='project_delete'),

]

projects/models.py
from django.db import models


# Create your models here.

class Status(models.TextChoices):
    UNSTARTED = 'u', "Not started yet"
    ONGOING = 'o', "Ongoing"
    FINISHED = 'f', "Finished"

class Course(models.TextChoices):
    UNSTARTED = 'a', "Course A"
    ONGOING = 'b', "Course B"
    FINISHED = 'c', "Course C"


class Project(models.Model):
    name = models.CharField(verbose_name="Enter your name", max_length=65, unique=True)
    status = models.CharField(verbose_name="Project status", max_length=1, choices=Status.choices)
    course = models.CharField(verbose_name="Course name", max_length=1, choices=Course.choices)
    timePreferences = models.CharField(verbose_name="I'd like to finish by", max_length=65)

    def __str__(self):
        return self.name

projects/forms.py
#-*- coding:utf-8 -*-
from .models import Project
from django import forms

class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = "__all__"

projects/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from .models import Project
from .forms import ProjectForm

# Create your views here.
# Functional based view
# Create a project
# def project_create(request):
#     if request.method == "POST":
#         form = ProjectForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect(reverse("projects:project_list"))
#     else:
#         form = ProjectForm()
#
#     return render(request, "projects/project_form.html", { "form": form, })
#
#
# # Retrieve project list
# def project_list(request):
#     projects = Project.objects.all()
#     return render(request, "projects/project_list.html", { "projects": projects,})
#
#
# # Retrieve a single project
# def project_detail(request, pk):
#     project = get_object_or_404(Project, pk=pk)
#     return render(request, "projects/project_detail.html", { "project": project, })
#
#
# # Update a single project
# def project_update(request, pk):
#     project_obj = get_object_or_404(Project, pk=pk)
#     if request.method == 'POST':
#         form = ProjectForm(instance=project_obj, data=request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect(reverse("projects:project_detail", args=[pk,]))
#     else:
#         form = ProjectForm(instance=project_obj)
#
#     return render(request, "projects/project_form.html", { "form": form, "object": project_obj})
#
#
# # Delete a single project
# def project_delete(request, pk):
#     project_obj = get_object_or_404(Project, pk=pk)
#     project_obj.delete()
#     return redirect(reverse("projects:project_list"))

# Class Based Views
from django.views.generic import ListView, DetailView, \
    CreateView, UpdateView, DeleteView

class ProjectListView(ListView):
    model = Project
    context_object_name = 'projects'

class ProjectDetailView(DetailView):
    model = Project

class ProjectCreateView(CreateView):
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy('projects:project_list')

class ProjectUpdateView(UpdateView):
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy('projects:project_list')

class ProjectDeleteView(DeleteView):
    model = Project
    success_url = reverse_lazy('projects:project_list')

projects/templates/projects/project_confirm_delete.html
<!DOCTYPE html>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ project }}"?</p>
    <input type="submit" value="Confirm" />
</form>

projects/templates/projects/project_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Project Detail</title>
</head>
<body>
<p> Name: {{ project.name }} | <a href="{% url 'projects:project_update' project.id %}">Update</a> |
    <a href="{% url 'projects:project_delete' project.id %}">Delete</a>
</p>
<p> Project Status: {{ project.get_status_display }} </p>
<p> <a href="{% url 'projects:project_list' %}">View All projects</a> |
    <a href="{% url 'projects:project_create'%}">New project</a>
</p>
</body>
</html>

projects/templates/projects/project_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if object %}Edit Project {% else %} Create New Project {% endif %}</title>
</head>
<body>
<h3>{% if object %}Edit Project {% else %} Create New Project {% endif %}</h3>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" class="btn btn-success" value="Submit"></p>
    </form>
</body>
</html>

projects/templates/projects/project_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Request List</title>
</head>
<body>
<h3>Request List</h3>
{% for project in projects %}
    <p>{{ forloop.counter }}. {{ project.name }} - {{ project.get_course_display }}
        (<a href="{% url 'projects:project_update' project.id %}">Update</a> |
        <a href="{% url 'projects:project_delete' project.id %}">Delete</a>)
    </p>
{% endfor %}

<p> <a href="{% url 'projects:project_create' %}"> + Start new request</a></p>
</body>
</html>